# Generated by Django 3.2.16 on 2023-10-22 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20231021_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text_eng',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_eng',
        ),
    ]
